### ISSUE TITLE
[Query] Hi, are you planning to finish the TODO?

### ISSUE THREAD

**Issue by zhengpeirong** [jainl28patel/AStack#1]
Dear author,

This is an awesome project. As far as I know, it is the only repository implementing TCP/UDP using `raw socket` in the open-source community. Do you plan to continue developing it?

Best Regards.

**Comment by jainl28patel** [comment]
Hello @zhengpeirong 

I am delighted to hear that you like the project. Actually its just a learning project that I did and I currently don't have any plans to continue it further. I may do some contributions during free time but there is currently no plan to make it production ready.

Between there are some application layers implementation of TCP/UDP available on github which are fully built. You can check them

Regards
